### ISSUE TITLE
Revamped Website

### ISSUE THREAD

**Issue by LittleTealeaf** [LittleTealeaf/littletealeaf.github.io#429]
# Tasks
 - [ ] Add Temporary File directory util in resources.js
 - [ ] Finalize Project Descriptors
 - [ ] Get Blog paging working
 - [ ] Create Header
 - [ ] Allow for use of "endpoints" in api fetching
 - [ ] Add the multi-page fetching for api
# Notes
 - Github has a metrics endpoint (see base github api link)
